### ISSUE TITLE
Integrate privacyidea server with the ¨verify email¨ function of keycloack.

### ISSUE THREAD

**Issue by sepp67** [privacyidea/keycloak-provider#130]
The function ¨verify email¨ in keycloack, generates a link that is sent via SMS or E-mail to the user when he is login in for the first time or when he changes his e-mail or phone number.

https://www.keycloak.org/docs/latest/server_admin/#con-required-actions_server_administration_guide
Look at: Defining actions required at login --> verify email

Is it possible that the Privacyidea server is sending a token Via SMS or E-mail to the user when the user is login for the first time or when he changes his e-mail or phone number ?

**Comment by basvandervlies** [comment]
Thanks we only need it when an user changes its mobile number . The verify email is already an action in keycloak and this can be set as action if the user changes its address. That is why we propose an "valid mobile" action.

**Comment by nilsbehlen** [comment]
this should be implemented in the server:
https://github.com/privacyidea/privacyidea/issues

**Comment by basvandervlies** [comment]
This is coming from an internal discussion as request we opened by netknights.  So your colleague opened it in the wrong project? Is it a keycloak issue.

**Comment by nilsbehlen** [comment]
Yes this should be implemented in the server, because if we do this, we want the option in all our plugins not just keycloak. I would guess that we do not even have to change a thing here, because SMS token are already usable and it just a matter of triggering an SMS at a certain point. That triggering is not something our provider should control but rather the server as the manageing component.
The new issue is https://github.com/privacyidea/privacyidea/issues/3491

**Comment by basvandervlies** [comment]
Thanks for the explanation @nilsbehlen
