### ISSUE TITLE
Old and new features don't work when trigger challenge is enabled

### ISSUE THREAD

**Issue by PlusaN** [privacyidea/keycloak-provider#168]
Keycloak: 22.0.5
keycloak-provider: 1.4.0 for KC22
PrivacyIDEA: 3.9.0

When "trigger challenge" is enabled, some provider settings do not work:
- ~~"Preferred Login Token Type" - at any value only TOTP token is displayed. On the PrivacyIDEA server the "preferred_client_mode" policy is not configured. On Keycloak v19 and keycloak-provider v1.1.0 such a problem is not observed (I think because the "Preferred client mode" feature was added in version 1.2.0). Maybe this parameter is now controlled only on the server side?~~
- "Auto-Submit OTP Length" - when entering X digits or more into the TOTP form, nothing happens.
- "Default OTP Text" - I realize that it only changes the default value, but it would be nice to be able to force this setting. This is useful when a user has two or more active tokens, especially with "challenge_text" policy and "Poll in browser" setting enabled. For example, if a user has TOTP and PUSH tokens, he will receive two identical messages in a row when he logs in.
![image](https://github.com/privacyidea/keycloak-provider/assets/61884717/ad0315b0-247d-4139-8a31-64efcdbe548f)

Offtopic: PrivacyIDEA-Provider-v1.4.0.KC22 work with Keycloak v23 or are there any problems with it? I haven't really looked into it, but visually I didn't find any problems.

**Comment by PlusaN** [comment]
Regarding "Preferred Login Token Type". I forgot that keycloak-provider has a debug mode....

The PrivacyIDEA server does send the parameter "preferred_client_mode": "interactive". This is quite strange though, since this setting is disabled in the policies.

**Comment by nilsbehlen** [comment]
Hi,
i somehow didn't see. So, one of the release versions is for **KC 22 and higher**, i tried to highlight that in the release section aswell because we got that question multiple times.

I do not know currently if `preferred_client_mode` defaults to interactive if not set.

I or @lukasmatusiewicz  will have to check if and why the Auto-Submit does not work.

I am also not satisfied with how the messages are composed in privacyidea. Contrary to that is our approach that privacyidea centralises everything and plugins should just display - with the option to configure per plugin in privacyidea.
So if we were to add a "overwrite privacyidea message" setting, it would be only until we have a proper implementation in privacyidea.

**Comment by lukasmatusiewicz** [comment]
Hi, @PlusaN ,
to auto-submit function:
can you check the console if something is logged about it?
