### ISSUE TITLE
Configuration of the jar  / mixed use of pi-otp and keycloak-otp

### ISSUE THREAD

**Issue by remkolodder** [privacyidea/keycloak-provider#7]
Hi,

Next to being unable to build the project in the first place, I can't seem to find where to configure the pi-server / realm and things.

That brings me also to the question of:

I have a group of LDAP-AD users, which I also have in PrivacyIdea.
I want to create a keycloak realm where the current ldap-ad users can use their current otp codes to authenticate towards this realm.

I also want to add external users (not in the AD) to the keycloak realm, and give them a privacyidea token so that they can use otp as well (or use the build in keycloak otp provider. I dont care much for the external users).

Thanks,
Remko

**Comment by Mipronimo** [comment]
Hey,
first of all you have to copy the theme privacyIDEA.ftl to `themes/base/login` and the jar to `standalone/deployments`.
After adding the files, go to your administration console to Authentication.
If you use the default authentication flow, you have to create a new one, because you can't edit the default one.
You can copy the browser flow.
Find the execution "*flow_name* Forms" and add privacyIDEA by clicking on "Actions" on the right side, "Add execution" and select the provider "PrivacyIDEA".
Now click on "Actions" and select "Config".
![Bildschirmfoto vom 2019-05-13 13-21-44](https://user-images.githubusercontent.com/35998229/57768114-3a6bce00-770b-11e9-84fa-d4ced82a370f.png)
Here you can edit your settings.
![Bildschirmfoto vom 2019-05-13 13-22-22](https://user-images.githubusercontent.com/35998229/57768139-46579000-770b-11e9-9935-f79b1c2177bd.png)
If you have set up everything, make sure, that privacyIDEA is set to "Required", so the users will be asked to enter their otps and bind the flow to your browser flow.
![Bildschirmfoto vom 2019-05-15 12-20-21](https://user-images.githubusercontent.com/35998229/57768401-d695d500-770b-11e9-8caf-2268676d778b.png)

**Comment by cornelinux** [comment]
> I also want to add external users (not in the AD) to the keycloak realm, and give them a privacyidea token so that they can use otp as well (or use the build in keycloak otp provider. I dont care much for the external users).

For all configuration questions (and I think this is especially a privacyIDEA Server questions, please got to https://community.privacyidea.org

**Comment by remkolodder** [comment]
> Hey,
> first of all you have to copy the theme privacyIDEA.ftl to `themes/base/login` and the jar to `standalone/deployments`.
> After adding the files, go to your administration console to Authentication.
> If you use the default authentication flow, you have to create a new one, because you can't edit the default one.
> You can copy the browser flow.
> Find the execution "_flow_name_ Forms" and add privacyIDEA by clicking on "Actions" on the right side, "Add execution" and select the provider "PrivacyIDEA".
> Now click on "Actions" and select "Config".
> ![Bildschirmfoto vom 2019-05-13 13-21-44](https://user-images.githubusercontent.com/35998229/57768114-3a6bce00-770b-11e9-84fa-d4ced82a370f.png)
> Here you can edit your settings.
> ![Bildschirmfoto vom 2019-05-13 13-22-22](https://user-images.githubusercontent.com/35998229/57768139-46579000-770b-11e9-9935-f79b1c2177bd.png)
> If you have set up everything, make sure, that privacyIDEA is set to "Required", so the users will be asked to enter their otps and bind the flow to your browser flow.
> ![Bildschirmfoto vom 2019-05-15 12-20-21](https://user-images.githubusercontent.com/35998229/57768401-d695d500-770b-11e9-8caf-2268676d778b.png)

Hi,

So this appears to get things in a configurable state. I have added the specific browser flow, but I get a null pointer exception now when I Try to login. There is not traffic to the OTP server at all.

**Comment by remkolodder** [comment]
> > I also want to add external users (not in the AD) to the keycloak realm, and give them a privacyidea token so that they can use otp as well (or use the build in keycloak otp provider. I dont care much for the external users).
> 
> For all configuration questions (and I think this is especially a privacyIDEA Server questions, please got to https://community.privacyidea.org

Right, I will post the specific privacyidea questions alongside of that on the community pages.

**Comment by Mipronimo** [comment]
> So this appears to get things in a configurable state. I have added the specific browser flow, but I get a null pointer exception now when I Try to login. There is not traffic to the OTP server at all.
This is fixed in #6 

So I can close it here, right?
